backend:
  name: github
  repo: Nhiokh/gatsby-blog

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Url du post (commencer par "/") }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Titre du post }
      - { name: body, label: Contenu du post, widget: "markdown" }
      - { name: image, label: Image de présentation }
